/**
 * Generate a simple text-based PDF report for a fraud case.
 * Pure JS — no external deps.
 */
export function downloadFraudReport(txn, user) {
  const lines = []
  const add = (t = '') => lines.push(t)

  add('SECUREFLOW — FRAUD REPORT')
  add('='.repeat(48))
  add('')
  add(`Generated: ${new Date().toLocaleString()}`)
  add(`Reported by: ${user?.name || 'User'} (${user?.email || 'N/A'})`)
  add('')
  add('TRANSACTION DETAILS')
  add('-'.repeat(48))
  add(`Merchant / Description : ${txn.merchant}`)
  add(`Account                : ${txn.accountName}`)
  add(`Amount                 : ${txn.amount.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`)
  add(`Date & Time            : ${new Date(txn.date).toLocaleString()}`)
  add(`Location               : ${txn.location || 'Unknown'}`)
  add(`Risk Level             : ${txn.riskLevel?.toUpperCase()}`)
  add(`Risk Score             : ${txn.riskScore}/100`)
  add(`Status                 : ${txn.status}`)
  add('')

  if (txn.explainable) {
    add('EXPLAINABLE AI BREAKDOWN')
    add('-'.repeat(48))
    add(`Summary: ${txn.explainable.summary}`)
    add('')
    add('Detailed reasons:')
    txn.explainable.reasons.forEach((r, i) => {
      add(`  ${i + 1}. ${r}`)
    })
    add('')
  }

  add('RECOMMENDED ACTIONS')
  add('-'.repeat(48))
  add('1. Freeze the affected account immediately if not already frozen.')
  add('2. Contact the bank fraud desk with this report reference.')
  add('3. Monitor related accounts for secondary activity.')
  add('')
  add('This report was generated by SecureFlow Explainable AI.')
  add('Case reference: SF-' + Date.now().toString(36).toUpperCase())
  add('')

  const text = lines.join('\n')

  // Minimal valid PDF with embedded text
  const escaped = text
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')

  // Split into PDF text lines with Tj
  const pdfLines = text.split('\n')
  let content = 'BT\n/F1 10 Tf\n50 780 Td\n14 TL\n'
  pdfLines.forEach((line, i) => {
    const safe = line.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
    if (i === 0) content += `(${safe}) Tj\n`
    else content += `T* (${safe}) Tj\n`
  })
  content += 'ET'

  const objects = []
  objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n')
  objects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n')
  objects.push(
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n'
  )
  objects.push(`4 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`)
  objects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj\n')

  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  objects.forEach((obj) => {
    offsets.push(pdf.length)
    pdf += obj
  })
  const xrefPos = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  for (let i = 1; i <= objects.length; i++) {
    pdf += String(offsets[i]).padStart(10, '0') + ' 00000 n \n'
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`

  const blob = new Blob([pdf], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `SecureFlow-Fraud-Report-${txn.id}.pdf`
  a.click()
  URL.revokeObjectURL(url)
}
